version: "3.8"
services:

  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks: 
      - todo-net
    volumes:
      - "./db-data/:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - "./pgadmin_data/:/var/lib/pgadmin"
    ports:
      - "5050:80"
    restart: always
    networks: 
      - todo-net
    depends_on:
      - db

  todo:
    build: 
      context: ./app
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PW=${POSTGRES_PW}
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - 8000:8000
    networks: 
      - todo-net

networks: 
  todo-net: